/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.ui;

import com.dev.model.Player;
import com.dev.model.Settings;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jdh6w
 */
public class InLobbyNB extends javax.swing.JPanel {

    private static InLobbyNB instance = null;

    public static InLobbyNB getInLobbyInstance(Settings settings, MainMenuNB mmnb){
        if(instance == null){
            instance = new InLobbyNB(settings, mmnb);
        }
        return instance;
    }

    public static InLobbyNB getInLobbyInstance(){
        if(instance == null){
            instance = new InLobbyNB();
        }
        return instance;
    }

    public Integer getRoomCodeValue(){
        Integer value = Integer.parseInt(roomCodeValue.getText());
        return value;
    }

    public void addPlayer(Player p){
        DefaultListModel dml = new DefaultListModel();
        if(players.size() < heldSettings.getPlayerCount()) {
            players.add(p);
        }
        for (Player player : players){
            dml.addElement(player.getName());
        }
        playerList.setModel(dml);
    }

    /**
     * Creates new form InLobbyNB
     */
    public InLobbyNB() {
        initComponents();
    }
    
    public InLobbyNB(Settings settings, MainMenuNB mmnb){
        initComponents();
        
        String randomCode = ((Integer)(Math.round(Math.round(Math.random() * 999999)))).toString();

        while(Integer.parseInt(randomCode) < 100000){
            randomCode = ((Integer)(Math.round(Math.round(Math.random() * 999999)))).toString();
        }

        roomCodeValue.setText(randomCode);
        
        heldSettings = settings;
        this.mmnb = mmnb;
        numPlayersLabel.setText("Max Players: "+settings.getPlayerCount());
        if(settings.getCategory().isEmpty()){
            settings.setCategory("All");
        }
        categoryLabel.setText("Category: "+settings.getCategory());
        numQuestionsLabel.setText(settings.getNumQuestions()+" Questions");
        timeLabel.setText(settings.getTime()+" seconds per question");
        pointsLabel.setText("Points to Win: "+settings.getPoints());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roomCodeLabel = new javax.swing.JLabel();
        roomCodeValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        numPlayersLabel = new javax.swing.JLabel();
        roomCodeButton = new javax.swing.JButton();
        categoryLabel = new javax.swing.JLabel();
        numQuestionsLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        pointsLabel = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        playerListLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(800, 600));

        roomCodeLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        roomCodeLabel.setLabelFor(roomCodeValue);
        roomCodeLabel.setText("Room Code:");

        roomCodeValue.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        roomCodeValue.setText("123456");

        playerList.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(playerList);

        numPlayersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numPlayersLabel.setText("Max Players: 8");

        roomCodeButton.setText("Toggle Room Code Hidden");
        roomCodeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomCodeButtonActionPerformed(evt);
            }
        });

        categoryLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        categoryLabel.setText("Category: All");

        numQuestionsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numQuestionsLabel.setText("Number of Questions: 10");

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeLabel.setText("30 seconds per question");

        pointsLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLabel.setText("Points to Win: 10000");

        startGameButton.setText("Start the Game!");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        playerListLabel.setLabelFor(playerList);
        playerListLabel.setText("Players:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerListLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numPlayersLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roomCodeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(categoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numQuestionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pointsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(roomCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomCodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomCodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomCodeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(roomCodeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numPlayersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numQuestionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerListLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(startGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void roomCodeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomCodeButtonActionPerformed
        // TODO add your handling code here:
        //hide room code or unhide it
        roomCodeValue.setVisible(!roomCodeValue.isVisible());
    }//GEN-LAST:event_roomCodeButtonActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
        //start the game
        mmnb.makeInGameMenu(this, heldSettings);
    }//GEN-LAST:event_startGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numPlayersLabel;
    private javax.swing.JLabel numQuestionsLabel;
    private javax.swing.JList<String> playerList;
    private javax.swing.JLabel playerListLabel;
    private javax.swing.JLabel pointsLabel;
    private javax.swing.JButton roomCodeButton;
    private javax.swing.JLabel roomCodeLabel;
    private javax.swing.JLabel roomCodeValue;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
    private Settings heldSettings;
    private MainMenuNB mmnb;
    private List<Player> players = new ArrayList<>();
    
    public String getRoomCode(){
        return roomCodeValue.getText();
    }
    
    public List<Player> getPlayers(){
        return players;
    }
    
}
