/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dev.ui;

import java.awt.Component;
import javax.swing.*;

import com.dev.model.Settings;

/**
 *
 * @author jdh6w
 */
public class MainMenuNB extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainMenuNB() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        newGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JearnBox");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("JearnBox");

        newGameButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        // TODO add your handling code here:
        //go to next menu
        this.remove(titleLabel);
        this.remove(newGameButton);
        System.out.println("removed");
        LobbySettingsNB lsnb = LobbySettingsNB.getLobbySettingsInstance(this);
        this.setContentPane(lsnb);
        lsnb.setVisible(true);
        for(Component c : lsnb.getComponents()){
            c.setVisible(true);
        }
    }//GEN-LAST:event_newGameButtonActionPerformed

    public void makeInLobbyMenu(LobbySettingsNB lsnb, Settings settings){
        this.remove(lsnb);
        InLobbyNB ilnb = InLobbyNB.getInLobbyInstance(settings, this);
        this.setContentPane(ilnb);
        ilnb.setVisible(true);
        for(Component c : ilnb.getComponents()){
            c.setVisible(true);
        }
        this.revalidate();
        this.repaint();
    }
    
    public void makeInGameMenu(InLobbyNB ilnb, Settings settings){
        this.remove(ilnb);
        GameplayNB gnb = new GameplayNB(settings, ilnb.getRoomCode(), ilnb.getPlayers());
        this.setContentPane(gnb);
        gnb.setVisible(true);
        for(Component c : gnb.getComponents()){
            c.setVisible(true);
        }
        this.revalidate();
        this.repaint();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                gnb.intro();
            }
        });
    }
    
    public void makeCategoryMenu(LobbySettingsNB lsnb){
        this.remove(lsnb);
        CategorySelector cs = new CategorySelector(this);
        this.setContentPane(cs);
        cs.setVisible(true);
        for(Component c : cs.getComponents()){
            c.setVisible(true);
        }
        this.revalidate();
        this.repaint();
    }
    
    public void backToLobbySettings(CategorySelector cs){
        this.remove(cs);
        LobbySettingsNB lsnb = LobbySettingsNB.getLobbySettingsInstance(this);
        if(!cs.getSelectedCategories().isEmpty()){
            lsnb.multipleCategories(cs.getSelectedCategories());
        } else {
            lsnb.notMultipleCategories();
        }
        this.setContentPane(lsnb);
        lsnb.setVisible(true);
        for(Component c : lsnb.getComponents()){
            c.setVisible(true);
        }
        this.revalidate();
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuNB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.out.println("main ran");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                System.out.println("run ran");
                new MainMenuNB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newGameButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
